- id: shellcheck
  name: shellcheck
  description: Shell scripts conform to shellcheck
  entry: shellcheck.sh
  language: script
  types: [shell]
  args: [-e, SC1091]
- id: trufflehog
  name: TruffleHog
  description: Detect secrets in your data
  entry: trufflehog.sh git file://. --since-commit HEAD --results=verified --fail
  language: script
  pass_filenames: false
