name: devprod-pre-commit
automerge_delay: 1
lang: unknown
lang_version: unknown
git:
  enable: true
codeowners:
  enable: true
renovatebot:
  enable: true
  automerge:
    enable: true
semaphore:
  enable: true
  pipeline_enable: false
